### PR TITLE
Specified the behavior of config.merge with arrays

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-123

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
@JKAussieSkater did you have a chance to look at this PR?

**Comment by JKAussieSkater** [comment]
Thanks! :+1:

**Comment by AurelioDeRosa** [comment]
That was quick, thank you!

**Comment by JKAussieSkater** [comment]
Sorry about the wait, I'd forgotten!

**Pull request merged**
