### PR TITLE
Improved "Sample Gruntfile" page

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-3

### CODE REVIEW

**Comment by JKAussieSkater** [comment]
😮!!!!!!!!!!
Amazing! Thanks!

**Comment by AurelioDeRosa** [comment]
Do you have an idea when this and the other changes will be live?

**Comment by JKAussieSkater** [comment]
I could do it now I think . . .
I just have to undo a certain change elsewhere in the repository first though, before propagating  changes.

**Comment by AurelioDeRosa** [comment]
That sounds cool. I think you meant that you have to fix https://github.com/gruntjs/grunt-docs/issues/156 first before publishing the changes, right?

**Comment by JKAussieSkater** [comment]
Spot on, exactly.
I can't fix it right now, but I can remove the link to the page from the navbar at the top so that the page can't be visited. Like a ghost, it's there, not visible. I'll do that now.

**Comment by JKAussieSkater** [comment]
@AurelioDeRosa, with the exception of the new documentation index page, all changes are pushed and live :+1:
Thanks again for your hard work with the contributions!

**Comment by AurelioDeRosa** [comment]
Awesome news! Thank you for pushing everything and for the grammar fixes. If you want, next time you can comment on the PR and I can fix them myself.

**Pull request merged**
