### PR TITLE
Grunt Brand guide

### PR DESCRIPTION
**Pull request by isaacdurazo**
@cowboy Here's the layout for the Brand Guide. You can start editing the content.

@vladikoff I have [another branch](https://github.com/isaacdurazo/gruntjs.com/tree/44-brand-guide)  under gruntjs.com for the assets and the styles needed for this page. I probably should wait to submit a PR, right?

### CODE REVIEW

**Comment by JKAussieSkater** [comment]
@isaacdurazo, not sure what you mean by "someone who can write copy for it" . . .
Could you explain what this PR needs to get pulled?

On another note, I'll try to create a version of this page which reciprocates the [jQuery logo spacing guidelines](https://brand.jquery.org/logos/#spacing-guidelines).

**Comment by JKAussieSkater** [comment]
Because we're trying to accomplish many tasks before releasing v1.0.0, I'm going to merge this as a pending draft. I'll remove the link from `Home.md` until further discussion agrees the page is ready.

**Comment by vladikoff** [comment]
:+1:

**Comment by JKAussieSkater** [comment]
Thanks vlad :smile:

**Pull request merged**
